Deactivate codecov

diff --git a/.github/workflows/hlwm.yml b/.github/workflows/hlwm.yml
--- a/.github/workflows/hlwm.yml
+++ b/.github/workflows/hlwm.yml
@@ -36,6 +36,6 @@ jobs:
         run: |
           ci/build.py --build-dir=build --cxx=g++-9 --cc=gcc-9 --build-type=Debug --ccache=.ccache --run-tests
 
-      - name: Codecov report
-        run: |
-          bash <(wget -O - https://codecov.io/bash) -f coverage.info || echo Warning: codecov report failed
+#      - name: Codecov report
+#        run: |
+#          bash <(wget -O - https://codecov.io/bash) -f coverage.info || echo Warning: codecov report failed
